CREATE TABLE users(
id INT AUTO_INCREMENT,
login VARCHAR (25) NOT NULL UNIQUE,
`checksum` VARCHAR (200) NOT NULL,
first_name VARCHAR (35) NOT NULL,
last_name VARCHAR (35) NOT NULL,
role_id INT DEFAULT 1 NOT NULL,
is_blocked BOOLEAN DEFAULT FALSE,
CONSTRAINT pk_user_id PRIMARY KEY (id),
CONSTRAINT fk_user_role_id FOREIGN KEY (role_id)
REFERENCES roles (id) ON UPDATE CASCADE ON DELETE RESTRICT
);